### ISSUE TITLE
Error: Unexpected SIGPIPE

### ISSUE THREAD

**Issue by Surdok** [NextFaze/ngx-translate-quickcreate#5]
Greetings.

I have used the extension previously on a windows machine and it worked like a charm.
However, when i transferred to a linux machine, the extension doesn't put the json in my clipboard as intended. I became curios and downloaded the source code.

When debugging the code, i end up with this error message :
`Error: Unexpected SIGPIPE
	at process.on (/usr/share/code/resources/app/out/bootstrap.js:5:192)
	at process.emit (events.js:182:13)`

Would be helpful if i knew how to exactly fix the problem.

**Comment by Surdok** [comment]
Never mind me, after some research through the internet, it turns out that copypaste from npm needs xclip to be installed on your linux machine.

Anyone who installs this extensions should install first xclip for linux.
